### ISSUE TITLE
Не работает входящий звонок

### ISSUE THREAD

**Issue by JerryLutor** [ViStepRU/callme#1]
Не работает исходящий звонок, bitrix присылает вот такие данные

array (
  'event' => 'ONEXTERNALCALLSTART',
  'data' =>.
  array (
    'PHONE_NUMBER' => '+XXXXXXXXXX',
    'PHONE_NUMBER_INTERNATIONAL' => '+XXXXXXXXXX',
    'EXTENSION' => '',
    'USER_ID' => '12',
    'CALL_LIST_ID' => '0',
    'LINE_NUMBER' => '',
    'CALL_ID' => 'externalCall.54d0d42ae705eafa02011574b5fc42.1XXXXXXXXXXX',
    'CRM_ENTITY_TYPE' => 'LEAD',
    'CRM_ENTITY_ID' => '0',
  ),
  'ts' => '1530176441',
  'auth' =>.
  array (
    'domain' => 'company.bitrix24.ua',
    'client_endpoint' => 'https://company.bitrix24.ua/rest/',
    'server_endpoint' => 'https://oauth.bitrix.info/rest/',
    'member_id' => '836938020c3cbef47d6364XXXXXX',
    'application_token' => 'XXXXXXXXXXXXXXXXXXXXXXXX',
  ),
)

Можно ли как то исправить ситуацию? Настройки сделаны из поста на habre

**Comment by SuperKa3a** [comment]
Тоже не работает исходящий звонок, Астериск возвращает ошибку "Extension does not exist."

**Comment by SuperKa3a** [comment]
Для того, чтобы астериск отвечал успешно, нужно убрать установку приоритета (установка приоритета - setPriority в методе OriginateCall класса CallAMI). После этого астериск отвечает успехом: "Originate successfully queued".

В статье на хабре встречаются ошибки, в частности есть синтаксические ошибки в настройке диалплана (";" в окончаниях строк), неправильный url для входящего вебхука (слеш на конце нужен, иначе формируется некорректная ссылка к методу завершения звонка)

**Comment by FessAectan** [comment]
Включайте дебаг в диалплане и смотрите что происходит.
