### ISSUE TITLE
Помогите с логикой входящих звонков.

### ISSUE THREAD

**Issue by sergesby** [ViStepRU/callme#4]
Не получается показывать карточки входящих звонков и т.п. в битриксе.

Судя по всему не могу понять логику, что с чем должно взаимодействовать.
Для чего нужен массив внешних номеров?

Может кто поделится мыслями?

Вот цитата с хабра:
> приходит звонок, какими-то внутренними средствами * адресуется конкретному внутреннему номеру — в битриксе показываем карточку

Ну вот приходит у меня звонок, звонит один из внутренних номеров, и на этом всё, ничего не всплывает в битриксе. Т.е. никакой регистрации входящего через CallMeIn.php не идёт.

Помогите плз....

**Comment by FessAectan** [comment]
Входящие звонки обрабатываются скриптом, который запущен через supervisor
Перечитайте раздел Настройка supervisor
в статье.

**Comment by sergesby** [comment]
Я извиняюсь, но он у меня настроен и работает:
`supervisorctl status callme
callme                           RUNNING   pid 2508, uptime 6:42:17`

я не могу сообразить что заставляет его "срабатывать". у меня идёт входящий звонок на внутренний номер сотрудника, но CallMeIn.php не отрабатывает.

Каким образом в Вашем примере вызывается 888999 в контексте incoming?
для чего нужен список внешних номеров ?

Подскажите плз.
Спасибо.

**Comment by ViStepRU** [comment]
Тут - http://sysadminz.ru/index.php?topic=14387.0
будет время - отвечу
